# Generated by Django 3.2.6 on 2021-08-24 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyShop',
            new_name='NewShop',
        ),
    ]
