# Generated by Django 3.0.5 on 2021-08-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0002_rename_myshop_newshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(blank=True, max_length=266, null=True)),
                ('aff_medium', models.CharField(blank=True, max_length=266, null=True)),
                ('aff_term', models.CharField(blank=True, max_length=266, null=True)),
                ('aff_campaign', models.CharField(blank=True, max_length=266, null=True)),
                ('aff_content', models.CharField(blank=True, max_length=266, null=True)),
                ('parent_org', models.CharField(blank=True, max_length=266, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='newshop',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
