# Generated by Django 3.0.5 on 2021-08-25 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0003_auto_20210825_0747'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compaign',
            new_name='Campaign',
        ),
        migrations.RenameModel(
            old_name='NewShop',
            new_name='Shop',
        ),
    ]
